name: Build

on: push

jobs:
  build_test_analyze:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        javaVersion: [8, 11, 17, 19]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.javaVersion }}
          distribution: temurin
          cache: maven
      - run: ./mvnw --batch-mode --update-snapshots verify
